### ISSUE TITLE
Fails to build on Debian testing

### ISSUE THREAD

**Issue by 0x8000-0000** [mbbill/flexbison#1]
$ make -f Makefile.ch9
flex -opurewc.lex.c purewc.l
cc -g   -c -o purewc.lex.o purewc.lex.c
purewc.l:32:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
 int argc;
 ^~~~
cc -g -o purewc purewc.lex.c
purewc.l:32:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
 int argc;
 ^~~~
flex -opurecalc.lex.c purecalc.l
bison -vd purecalc.y
cc -g   -c -o purecalc.lex.o purecalc.lex.c
In file included from purecalc.l:14:0:
purecalc.tab.h:86:21: warning: ‘struct pcdata’ declared inside parameter list will not be visible outside of this definition or declaration
 int yyparse (struct pcdata *pp);
                     ^~~~~~
cc -g   -c -o purecalc.tab.o purecalc.tab.c
purecalc.tab.c:143:21: warning: ‘struct pcdata’ declared inside parameter list will not be visible outside of this definition or declaration
 int yyparse (struct pcdata *pp);
                     ^~~~~~
purecalc.tab.c:1024:1: error: conflicting types for ‘yyparse’
 yyparse (struct pcdata *pp)
 ^~~~~~~
purecalc.tab.c:143:5: note: previous declaration of ‘yyparse’ was here
 int yyparse (struct pcdata *pp);
     ^~~~~~~
purecalc.tab.c: In function ‘yyparse’:
purecalc.tab.c:1193:16: error: too few arguments to function ‘yylex’
       yychar = yylex (&yylval);
                ^~~~~
In file included from purecalc.y:26:0:
purecalc.lex.h:321:12: note: declared here
 extern int yylex \
            ^~~~~
<builtin>: recipe for target 'purecalc.tab.o' failed
make: *** [purecalc.tab.o] Error 1
$ cc --version
cc (Debian 6.2.1-5) 6.2.1 20161124
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ flex --version
flex 2.6.1
$ bison --version
bison (GNU Bison) 3.0.4
Written by Robert Corbett and Richard Stallman.

Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by shawnyangcis** [comment]
There are some syntax errors like ";" in incorrect position.You should fix it by yourself.
